### ISSUE TITLE
Repos

### ISSUE THREAD

**Issue by erwin-gimmick** [erwin-gimmick/gimmickmedia#24]
Shandy, thank for the work first.
btw, buat reposnya krn behubungan ama clientny langsung, kt musti jaga privasiny krn itu musti kt bikin private itu repo" nya yg kt pake itu... itu bs dtransfer biar kt bs setting ke private repo

**Comment by shandya** [comment]
![screenshot-github com 2016-03-06 11-56-04](https://cloud.githubusercontent.com/assets/4597656/13552372/8bf7af42-e392-11e5-8f1b-1ff5832bf537.png)

Iya sama2. Untuk transfer reponya sudah saya requestkan ya. Mohon diaccept.

**Comment by erwin-gimmick** [comment]
Aneh bisa di abort n retransfer lagi ga... sy ga dapat email anehnya.

**Comment by shandya** [comment]
Sudah diretransfer lagi

**Comment by erwin-gimmick** [comment]
udah... tq..
